### ISSUE TITLE
Support for Meizu Phone with flymeOS

### ISSUE THREAD

**Issue by olbb** [olbb/scrcpy#1]
In Meizu phone,there is an error case by MzNightModeManager

>Surface: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
        at android.os.Handler.<init>(Handler.java:200)
        at android.os.Handler.<init>(Handler.java:114)
        at com.meizu.nightmode.MzNightModeManager.<init>(MzNightModeManager.java:158)
        at com.meizu.nightmode.MzNightModeManager.getDefault(MzNightModeManager.java:313)
        at android.graphics.Canvas.<init>(Canvas.java:2606)
        at android.view.Surface$CompatibleCanvas.<init>(Surface.java:631)
        at android.view.Surface$CompatibleCanvas.<init>(Surface.java)
        at android.view.Surface.<init>(Surface.java:107)
        at android.media.MediaCodec.createInputSurface(Native Method)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:69)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:28)
        at com.genymobile.scrcpy.Server.main(Server.java:110)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:277)

**Comment by callmexss** [comment]
hello there, can you give some more detail instructions about how can I use this patch?

**Comment by olbb** [comment]
@callmexss  you can just compile the scrcpy's android project and get the scrcpy.jar and replace it with the officecal scrcpy.jar
